version: '3'

services:
  api:
    build: .
    ports:
    - "8888:8888"

  db:
    image: "postgres:11"
    container_name: "postgres_database"
    environment:
      - POSTGRES_PASSWORD=1337
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "55432:5432"