version: '3'

services:
  api:
    restart: always
    build: .
    ports:
    - "8888:80"
    depends_on:
      - db

  db:
    restart: always
    image: "postgres:11"
    container_name: "postgres_database"
    environment:
      - POSTGRES_PASSWORD=1337
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "65432:5432"